---
base_packages:
  - vim
  - less
  - pv
  - pigz
  - zstd
  - btop
  - file
  - postfix
  - smartmontools
  - rsync
  - tar
  - screen
  - htop
  - bash-completion
  - curl
  - wget
  - btop
  - btrfs-progs
base_packages_rhel:
  - compsize
base_packages_ubuntu:
  - btrfs-compsize
  - libsasl2-modules

ansible_ssh_private_key_file: /root/.ssh/svc_ansible
ansible_user: svc_ansible
ansible_become: true
ansible_python_interpreter: /usr/bin/python3

