---
- name: Install MediaMTX
  hosts: picams:babycam:cameras:picamsir
  become: true
  gather_facts: true
  strategy: linear
  tasks:

    - name: Install MediaMTX
      include_role:
        name: mediamtx
        tasks_from: install.yaml
        vars_from: mediamtx.yaml

