---
- name: Install MediaMTX
  hosts: all
  become: true
  gather_facts: true
  strategy: linear
  tasks:

    - name: Install MediaMTX
      include_role:
        name: mediamtx
        tasks_from: install.yml
        vars_from: mediamtx.yaml

