---
- name: Setup Yubikey FIDO2 LUKS
  hosts: all
  become: true
  gather_facts: true
  tasks:

    - name: Setup Yubikey FIDO2 LUKS
      include_role:
        name: luks
        tasks_from: setup_yubikey_fido2.yaml
      when: luks_yubikey_fido2 | default(false) | bool

    - name: Reboot system
      ansible.builtin.reboot:
        pre_reboot_delay: "{{ 15 | random(start=5) }}"
        reboot_timeout: "{{ reboot_timeout | default(600) }}"
        post_reboot_delay: "{{ post_reboot_delay | default(60) }}"
        test_command: hostname
      when:
        - allow_reboot | default(false) | bool
        - reboot_needed | default(false) | bool
