---
- name: Install OpenWRT update
  hosts: openwrt
  become: true
  gather_facts: false
  strategy: linear
  roles:
    - gekmihesg.openwrt
  tasks:
    - name: Install OpenWRT update
      include_role:
        name: openwrt
        tasks_from: update.yaml
