---
- name: Install python3-apt if missing
  hosts: all
  become: true
  gather_facts: true
  strategy: linear
  tasks:

    - name: Install python3-apt if missing
      package:
        name: python3-apt
        state: present
      when: ansible_distribution == "Ubuntu"