---
#Reboot system
- name: Reboot system
  hosts: all
  gather_facts: no
  become: yes
  tasks:

    - name: Reboot system
      reboot:
        pre_reboot_delay: "{{ 15 | random(start=5) }}"  #Needed on some OS's
        reboot_timeout: "{{ reboot_timeout | default(600) }}"
        post_reboot_delay: "{{ post_reboot_delay | default(60) }}"
        test_command: hostname
