---
- name: Set hostname
  hosts: all
  gather_facts: no
  become: yes
  tasks:

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        use: systemd
