---
- name: Install package updates
  hosts: all
  become: true
  gather_facts: true
  tasks:

    - name: Install package updates
      include_role:
        name: packages
        tasks_from: update.yaml
