---
- name: Add USB keyfile to LUKS
  hosts: all
  become: True
  gather_facts: False
  strategy: mitogen_linear
  vars_files:
    - "private/vars/luks_common.yaml"
    - "private/vars/{{ inventory_hostname }}.yaml"
  tasks:
    - name: Add USB keyfile to LUKS
      include_role:
        name: usb_luks
        tasks_from: add_usb_key.yaml
