---
- name: Update with apt
  when: ansible_pkg_mgr == "apt"
  block: 

    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: full
        autoremove: true
      register: apt_result
      notify: Reboot system
      changed_when: apt_result.changed

    - name: Show apt changes (summary)
      ansible.builtin.debug:
        msg: "{{ apt_result }}"
