---
- name: Update packages
  ansible.builtin.apt:
    name: "*"
    update_cache: yes
    cache_valid_time: 3600
    state: latest
  register: update_output

- name: Updates
  debug:
    msg: "{{ update_output.stdout_lines }}"

- name: Autoremove
  ansible.builtin.apt:
    autoremove: yes
  when: ansible_facts.packages['apt']
