---
- name: Remount btrfs mounts with higher compression
  become: true
  ansible.posix.mount:
    path: "{{ item }}"
    state: remounted
    opts: "compress-force=zstd:{{ btrfs_comp_high | default(2) }}"
  loop: "{{ btrfs_compressed_mounts }}"
  when:
    - (ansible_mounts
        | selectattr('mount', 'equalto', item)
        | map(attribute='fstype')
        | first
        | default('')) == 'btrfs'