---
- include_tasks: prep.yaml

- include_tasks: upcompression.yaml

- include_tasks: snap.yaml
  when: |
    ( ansible_facts.packages['snapd'] | default(false) | bool )
    or ( dpkg_snapd is defined and dpkg_snapd.rc is defined and dpkg_snapd.rc == 0 )

- include_tasks: apt.yaml
  when: ansible_facts.packages['apt']

- include_tasks : pi_firmware.yaml
  when: pi_firmware_update

- include_tasks: remount.yaml

### need dnf/yum equiv

- name: fstrim
  include_tasks: fstrim.yaml

- name: Reboot system
  reboot:
    pre_reboot_delay: "{{ 15 | random(start=5) }}"  #Needed on some OS's
    reboot_timeout: "{{ reboot_timeout | default(600) }}"
    post_reboot_delay: "{{ post_reboot_delay | default(60) }}"
    test_command: hostname
