---
- name: Install NUT server
  ansible.builtin.package:
    name: nut-server
    state: present

- name: Setup nut.conf
  ansible.builtin.template:
    src: nut-server.conf.j2
    dest: /etc/nut/nut.conf
    owner: root
    group: nut
    mode: '0640'
  notify: restart nut-server

- name: Setup ups.conf
  ansible.builtin.template:
    src: ups-cp.conf.j2
    dest: /etc/nut/ups.conf
    owner: root
    group: nut
    mode: '0640'
  notify: restart nut-server

- name: Setup upsd.conf
  ansible.builtin.template:
    src: upsd-server.conf.j2
    dest: /etc/nut/upsd.conf
    owner: root
    group: nut
    mode: '0640'
  notify: restart nut-server

- name: Flush handlers to restart nut-server
  ansible.builtin.meta: flush_handlers



- name: Verify with localhost upsc nutdev1@localhost
  ansible.builtin.command:
    cmd: upsc nutdev1@localhost
  changed_when: false
  check_mode: false
