---
btrbk_transaction_log: /var/log/btrbk.log
btrbk_timestamp_format: long
btrbk_stream_buffer: 256m
btrbk_stream_buffer_remote: 500m
btrbk_snapshot_dir: .btrbk_snapshots
btrbk_snapshot_create: onchange
btrbk_incremental: "yes"
btrbk_preserve_hour_of_day: 3
btrbk_preserve_day_of_week: sunday
btrbk_snapshot_preserve_min: 1d
btrbk_snapshot_preserve: 24h 7d 2w 0m 0y
btrbk_target_preserve_min: "no"
btrbk_target_preserve: 0h 14d 5w 1m 1y
btrbk_archive_preserve_min: latest
btrbk_archive_preserve: 0h 1d 1w 1m 1y
btrbk_ssh_identity: /root/.ssh/btrbk.key
btrbk_ssh_user: root
btrbk_ssh_compression: "no"
btrbk_ssh_cipher_spec: default
btrbk_lockfile: /var/lock/btrbk.lock
btrbk_btrfs_commit_delete: "no"

# 30mbit
btrbk_stream_compress: zstd
btrbk_stream_compress_level: 2
btrbk_stream_compress_threads: 4
btrbk_stream_compress_adapt: "yes"

# 1000mbit
# btrbk_stream_compress no

# 100mbit
#btrbk_stream_compress: zstd
#btrbk_stream_compress_level: 15
#btrbk_stream_compress_threads: 4
#btrbk_stream_compress_adapt: no

btrbk_target_packages:
  - btrfs_utils
  - mbuffer
  - zstd
