---
- name: Reload systemd timesyncd configuration
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
  listen: restart timesyncd

- name: Regenerate grub config
  ansible.builtin.command:
    cmd: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: ansible_facts['os_family'] == 'RedHat'
  listen: update grub

- name: Regenerate grub config
  ansible.builtin.command:
    cmd: update-grub
  when: ansible_facts['os_family'] == 'Debian'
  listen: update grub