---
- name: Add Inkscape PPA
  ansible.builtin.apt_repository:
    repo: ppa:inkscape.dev/stable
    state: present

- name: Install Inkscape
  ansible.builtin.apt:
    name: inkscape
    state: present